[package]
name = "dcm-dicom"
description = "DICOM metadata and pixel decode for dcm2niix-rs"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
dcm-core = { workspace = true }
dicom-object = { workspace = true }
dicom-core = { workspace = true }
dicom-dictionary-std = { workspace = true }
dicom-pixeldata = { workspace = true }
crc32fast = { workspace = true }
flate2 = { workspace = true }
jpeg-decoder = "0.3"
memmap2 = "0.9"
rayon = "1.10"
