[package]
name = "dcm-bids"
description = "BIDS JSON sidecar writer for dcm2niix-rs"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
dcm-core = { workspace = true }
dcm-dicom = { workspace = true }
dcm-nifti = { workspace = true }
serde_json = { workspace = true }
